### ISSUE TITLE
No camera permission requested

### ISSUE THREAD

**Issue by Khmerj** [rocwang/grocer-issues#120]
App installed on OnePlus 7. When I try to scan a product to search, it says that I did not give permission for app to use the camera. But when I go to permissions, it says that no permissions was requested. Worked fine on OnePlus 5

**Smartphone (please complete the following information):**
 - Device: OnePlus 7
 - OS: Oxygen OS 11.GM57AA
 - Browser: NA
 - Version: 11

**Comment by rocwang** [comment]
Please try the following:

Manually typing [grocer.nz](http://grocer.nz/) in Chrome and ignore any redirection prompt from Chrome if it ask for jumping to the installed app.

Taps the padlock icon in the address bar, you should see a site setting popup as below:

![permissions](https://user-images.githubusercontent.com/1286164/222930142-dc04543f-643a-4f35-99a3-e546d5217ea6.jpeg)

Then tap “Permission”, turn on the camera access for Grocer as below:

![camera](https://user-images.githubusercontent.com/1286164/222930148-5c6361b5-43c1-4950-bc44-516c0a590175.jpeg)

Now go back to the install app, which should have a working camera for scanning by then.

Alternatively, you may long press the install app icon, select “Site Settings” and grant camera access there.

**Comment by Khmerj** [comment]
Thank you 🙂
________________________________
