### ISSUE TITLE
Prices won't load. The search feature won't bring up products and their prices

### ISSUE THREAD

**Issue by Hannahprestidge** [rocwang/grocer-issues#130]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rocwang** [comment]
Does it work for you if you go to https://grocer.nz/ ?

**Comment by Hannahprestidge** [comment]
No still doesn't work if you search for a product. If I type in 'watties'  nothing come up

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rocwang** [comment]
Could you open the following in your browser?

* https://search.grocer.nz/ It should say "Meilisearch is running"
* https://backend.grocer.nz/updatedAt It should return a number

**Comment by Hannahprestidge** [comment]
1680557689


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Hannahprestidge** [comment]
I got this app going for about an hour and now has stopped again

**Comment by rocwang** [comment]
If you go to [https://search.grocer.nz/health](https://search.grocer.nz/health), does it show "{"status":"available"}"?
