### ISSUE TITLE
Show available store after searching a product

### ISSUE THREAD

**Issue by JLWJL** [rocwang/grocer-issues#52]
Currently if I have stores selected and search a product that's unavailable among them, the app shows no result. I have to remove all stores and search so that I can possibly find the product, but I wouldn't know at which stores I can buy them.

**Comment by rocwang** [comment]
Yes, the current behavior is Grocer only searches within the selected stores and shows products if at least one store has it.

This feature request is the other way around: Search across all possible stores and let you know where you can buy it, no matter where the store is.

Engineering wise, this wouldn't be hard, however given Grocer support 400+ stores, the UI might need a bit of consideration.

**Comment by rocwang** [comment]
Merged with #5
