### ISSUE TITLE
No New World or Pak n Save stores in Nelson Tasman region 

### ISSUE THREAD

**Issue by pipmum** [rocwang/grocer-issues#56]
Makes app almost useless for us over 100k people living here. Can't compare between our major grocers. Any plans to fix this? Thanks

**Comment by rocwang** [comment]
The way Grocer gets the price data currently is scraping from the official shopping websites/apps.

A lot of Pak'nSave and New World stores are not open for online shopping yet including the Pak'nSave Richmond store in Nelson. So Grocer can't support those stores at the moment.

It looks like Foodstuffs is working on [supporting online shopping for more stores in South Island](https://www.paknsave.co.nz/more/south-island-online). However Pak'nSave Richmond is not coming soon.
