### ISSUE TITLE
Prices not accurate 

### ISSUE THREAD

**Issue by Col24** [rocwang/grocer-issues#63]
The prices appear to be those of the previous week (August 25 - 31) and have not updated to this weeks' prices. This is across the board. This is for a range of products as I check the app each week but double checked on the supermarket websites.

I've attached a screenshot of the example of the problem. It's not just with this product, this is just a snapshot  - note: the new world app used did have the correct location. It's with products at countdown and pak n save too.

This problem was on Google Chrome on a windows desktop and Chrome on a Samsung A52s, as well as the grocer.nz app on Samsung A52s.

![Screenshot_20220802-075720_Samsung Internet](https://user-images.githubusercontent.com/110410530/182235168-27d625b8-4112-466b-b075-232fdf489ddb.jpg)
![Screenshot_20220802-075704_New World](https://user-images.githubusercontent.com/110410530/182235178-7c896c83-b1f1-4ee3-bfe1-ab355cdaaf72.jpg)

**Comment by rocwang** [comment]
Thanks for the issue report. I can confirm that Grocer stopped updating the pricing data since 2022-07-29.
I've fixed that. The price should be updated later today.

**Comment by rocwang** [comment]
<img width="728" alt="Screen Shot 2022-08-02 at 3 16 36 PM" src="https://user-images.githubusercontent.com/1286164/182284341-b6bf454b-ebf3-4706-a00c-539049c83b9c.png">

The price data has been updated.
