### ISSUE TITLE
App crashing(brave stops responding) when trying to search

### ISSUE THREAD

**Issue by memskez** [rocwang/grocer-issues#66]
If I can provid anymore information please let me know but on android using brave as my default browser the grocer app hangs up and crashing when switching to search. Don't even have to type anything or search. It loads the default bananas etc to display but then hangs.

**Comment by rocwang** [comment]
I have a few questions:

* Does it constantly happen?

  Last night there was a traffic surge for a while, which brought down the search server.

* How many stores were selected?

Right now up to 20 stores can be selected. There is a known issue that if many stores are selected with products in the shopping list, the planning function will have a hard time and freeze the app.

**Comment by memskez** [comment]
Yep, it has been happening for multiple days now. Since the last update possibly? Works fine on desktop. Partners is consistently crashing as well, believe she is using chrome as default, but sometimes hers loads after hanging for a bit(seemingly loading the default items on the search page). I can't get mine to function normally. I can open chrome separately and load the web address and it works

Three stores are selected. Papamoa Pak n Save, Te Puke Countdown and Te Puke New World.

**Comment by Renatori** [comment]
I've been having the same issue for a couple of weeks now and I can confirm it has nothing to do with the built in ad blocker whether it's on or off

**Comment by rocwang** [comment]
I wonder if it works for you under a new private window in Brave iOS?

**Comment by memskez** [comment]
I am on Android and a private window does not make a difference. Tried app and straight in the browser. (I understand it runs off the same but just incase there's a difference)

**Comment by rocwang** [comment]
Apologies for you frustrating experience. Would you be able to share a screen recording on this issue?

**Comment by memskez** [comment]
Managed to find a way to get the search going before it crashed but as you can see it still hangs considerably.  

Attached one with shield, one without and the way to get it to search without crashing. 

https://user-images.githubusercontent.com/32346841/186277434-0c02f544-ff81-432f-ba0a-0a163ff59224.mp4


https://user-images.githubusercontent.com/32346841/186277439-cf836158-da52-46fd-b835-7a6c7d97fb58.mp4


https://user-images.githubusercontent.com/32346841/186277442-ba05449a-e934-4b99-98a8-da016773c359.mp4

**Comment by rocwang** [comment]
I think I find the culprit that led to the poor search experience — the experimental “refinement” feature under search.

I’m releasing a new version that will have this feature disabled. 

You would see a in-app update some time later which should fix this problem I believe.

Let me know if it works for you please.

Cheers.
Roc

**Comment by Renatori** [comment]
It's not crashing anymore!!! Thank you for fixing it

**Comment by memskez** [comment]
Working like normal again, absolute legend! Thank you!
