### ISSUE TITLE
No Countdown Greerton 

### ISSUE THREAD

**Issue by Col24** [rocwang/grocer-issues#69]
Hey team, looks like there is no Countdown Greerton as an option anymore. Think it might have happened in the latest update.

Thanks!

**Comment by rocwang** [comment]
Yes, it's related to the recent update as I just integrated the official Countdown price feed into Grocer.
The feed has a few stores missing, but I can fix it by using the website data.

Will let you know once Countdown Greerton is back. Shouldn't be able to get it back later today.

Thanks for the issue report!

**Comment by rocwang** [comment]
Countdown Greerton should be back in the store list now.
If now, you might need to wait until tomorrow as the list could be cached.
