### ISSUE TITLE
Countdown store disappeared from list

### ISSUE THREAD

**Issue by bilembambudina** [rocwang/grocer-issues#76]
Countdown auckland Victoria street west has disappeared from the list. It is still available for online shopping on the countdown website.

**Comment by rocwang** [comment]
Thanks for the issue report.

I'm integrating Countdown's official price feed which may have certain stores missed, but I managed to restored the "Countdown Auckland Victoria Street West" store, which should appear in the app later today.

**Comment by rocwang** [comment]
"Countdown Auckland Victoria Street West" is back to the store list now.
